site_name: Arquitetura de Dados - Delta & Iceberg
theme:
  name: material

nav:
  - 'Home': index.md
  - 'Apache Spark': spark.md
  - 'Laboratorio Delta x Iceberg': laboratorio.md
  - 'Apache Iceberg': iceberg.md
  - 'Delta Lake': delta.md